version: "3.2"

services:
  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-xenon
    hostname: chrome
    container_name: chrome
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
